const { Parser } = require("node-sql-parser");
const parser = new Parser();
const sql = `
WITH LineItems AS (
    -- CTE 1: Denormalize the core order details and calculate revenue per line
    SELECT
        o.id AS order_id,
        o.order_date,
        o.status,
        o.customer_id,
        o.sales_rep_id,
        p.name AS product_name,
        cat.name AS category_name,
        o.quantity,
        p.price,
        (o.quantity * p.price) AS revenue,
        a.country AS shipping_country,
        a.city AS shipping_city
    FROM Orders o
    JOIN Products p ON o.product_id = p.id
    JOIN Categories cat ON p.category_id = cat.id
    LEFT JOIN Addresses a ON o.address_id = a.id
),
CustomerAnalytics AS (
    -- CTE 2: Aggregate historical data to determine customer value and tiers
    SELECT
        c.id AS customer_id,
        c.name AS customer_name,
        c.loyalty_points,
        COUNT(DISTINCT li.order_id) AS total_orders,
        SUM(li.revenue) AS lifetime_value,
        CASE
            WHEN SUM(li.revenue) > 1000 THEN 'Platinum'
            WHEN SUM(li.revenue) > 500 THEN 'Gold'
            ELSE 'Silver'
        END AS customer_tier
    FROM Customers c
    LEFT JOIN LineItems li ON c.id = li.customer_id
    GROUP BY c.id, c.name, c.loyalty_points
),
SalesRepRanking AS (
    -- CTE 3: Calculate total revenue generated by each employee and rank them by region
    SELECT
        e.id AS rep_id,
        e.name AS rep_name,
        e.region,
        SUM(li.revenue) AS total_sales_generated,
        RANK() OVER(PARTITION BY e.region ORDER BY SUM(li.revenue) DESC) AS regional_rank
    FROM Employees e
    LEFT JOIN LineItems li ON e.id = li.sales_rep_id
    GROUP BY e.id, e.name, e.region
)
-- Final Output: Stitching the aggregations back to the individual orders
SELECT
    ca.customer_name,
    ca.customer_tier,
    ca.lifetime_value,
    li.order_id,
    li.order_date,
    li.product_name,
    li.category_name,
    li.revenue AS order_revenue,
    li.shipping_city,
    sr.rep_name AS handled_by_rep,
    sr.regional_rank AS rep_regional_rank,
    -- Calculate what percentage this specific order makes up of the customer's total lifetime spend
    ROUND((li.revenue / NULLIF(ca.lifetime_value, 0)) * 100, 2) AS pct_of_customer_ltv
FROM LineItems li
JOIN CustomerAnalytics ca ON li.customer_id = ca.customer_id
JOIN SalesRepRanking sr ON li.sales_rep_id = sr.rep_id
WHERE li.status = 'delivered'
ORDER BY ca.lifetime_value DESC, li.order_date DESC;
`;

let ast = parser.astify(sql);
if (Array.isArray(ast)) ast = ast[0];

if (ast.with) {
    for (const cte of ast.with) {
        try {
            console.log("SQLIFY", cte.name.value, ":", parser.sqlify(cte.stmt));
        } catch (e) {
            console.log("SQLIFY FAIL", cte.name.value, e.message);
        }
    }
}
